### PR TITLE
Open source is not a place for politics. 

### PR DESCRIPTION
**Pull request by klevunin**
You do not know anything about what is happening in Ukraine. And when you understand you will be ashamed that you are in politics.

### CODE REVIEW

**Comment by Ocramius** [comment]
Piss off.

**Comment by Ocramius** [comment]
Blocked user too.

**Comment by Ocramius** [comment]
Just checked a bit: new account that started to send patches against projects supporting Ukraine.

To be **extremely** clear, what Russia is committing in Ukraine is **genocide**.

I have friends and  acquaintances in Ukraine, and no amount of brain-washing will steer me off denouncing the inhuman acts performed by the anachronistically fascist Russia of 2022.

**Comment by asgrim** [comment]
As a fellow Roave maintainer, I second what @Ocramius said entirely.

**Pull request closed without merging**
