### PR TITLE
Dropped all build scripts, moved to Roave/SecurityAdvisoriesBuilder

### PR DESCRIPTION
**Pull request by Ocramius**
Depends on Roave/SecurityAdvisoriesBuilder#1

@fabpot before merging this particular one, I'd need you to point your git hook to https://roave-security-advisories.herokuapp.com/ whenever you have time.

### CODE REVIEW

**Comment by fabpot** [comment]
@Ocramius Done

**Comment by Ocramius** [comment]
:+1: thanks!

**Comment by Ocramius** [comment]
Hmm, we could do that, but it is tricky

**Comment by Ocramius** [comment]
Shipping for now - additional testing to be added can be indeed added later on.

**Pull request merged**
