### PR TITLE
Committing generated "composer.json" file as per "2016-07-18T19:09:42+00:00"

### PR DESCRIPTION
**Pull request by graste**
The Guzzle CVE https://github.com/FriendsOfPHP/security-advisories/pull/154 made me wonder, whether this repository had been updated with this information. Updates other libraries as well.

### CODE REVIEW

**Comment by Ocramius** [comment]
@graste this should have been done automatically... Gimme a few to check what went wrong :-\

**Comment by graste** [comment]
Was wondering why this awesome repo felt a bit outdated. :+1:

**Comment by Ocramius** [comment]
Handled via https://github.com/Roave/SecurityAdvisories/commit/303b317d4f5eedfdb6e571b511f1c9d8ce038df2

Apparently, the server that hosts the github webhook callback disabled `ext-dom` for some reason, and that caused the `composer install` to fail.

**Comment by graste** [comment]
Thanks. :-)

**Pull request closed without merging**
