### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by slash3b**
Due to already done transition to Github actions status batch might be updated : )

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This no longer links to the CI?

**Comment by GrahamCampbell** [comment]
Also, there are no actions builds... https://github.com/Roave/SecurityAdvisories/actions

**Comment by Ocramius** [comment]
Ah yes, link is indeed missing. That would be https://github.com/Roave/SecurityAdvisoriesBuilder/actions?query=workflow%3A%22Hourly+build%22

**Comment by GrahamCampbell** [comment]
Sent a PR just before your comment. ;)

**Pull request merged**
